SuperBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

]

blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # path('', views.PostListView.as_view(), name='post_list'),
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.strftime('%m'),
                                                 self.publish.strftime('%d'),
                                                 self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f"Komentarz dodany przez {self.name} dla posta {self.post}."



blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=250)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from SuperBlog.secret import mail
from .forms import EmailPostForm, CommentForm, SearchForm
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity


# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month,
                             publish__day=day)
    comments = post.comments.filter(active=True)
    if request.method == 'POST':  # komentarz zostal opublikowany
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)  # utworzenie obieku Comment
            new_comment.post = post  # przypisanie komentarza do biezacego posta
            new_comment.save()  # zapisanie komentarza w bazie danych
    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similiar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similiar_posts = similiar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/post/detail.html',
                  {'post': post, 'comments': comments, 'comment_form': comment_form, 'similiar_posts': similiar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) zachęca do przeczytania "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Przeczytaj post "{}" na stronie {}\n\n Komentarz dodany przez {}: {}'.format(post.title,
                                                                                                    post_url,
                                                                                                    cd['name'],
                                                                                                    cd['comments'])
            send_mail(subject, message, mail, [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            # search_query = SearchQuery(query)
            results = Post.published.annotate(similarity=TrigramSimilarity('title',query)+TrigramSimilarity('body',query),).filter(similarity__gte=0.1).order_by('-similarity')
            # results = Post.objects.annotate(rank=SearchRank(search_vector, search_query)).filter(rank__gte=0.1).order_by('-rank')
    return render(request, 'blog/post/search.html', {'form': form, 'query': query, 'results': results})

templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>SuperBlog</h2>
        <p>Ten blog jest super.</p>
        <p>Liczba opublikowanych postów: {% total_posts %}</p>
        <h3>Najnowsze posty</h3>
        {% show_latest_posts 3 %}
        <h3>Najczęściej komentowane posty</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
            <li>
                <a href = "{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
            {% endfor %}
        </ul>
        <p>
            <a href="{% url "blog:post_feed" %}">Subskrybuj kanał RSS </a>
        </p>
        <p>
            <a href="{% url "blog:post_search" %}"> Czegoś szukasz? </a>
        </p>


    </div>
</body>
</html>

templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href ="?page={{ page.previous_page_number }}">Poprzedni</a>
        {% endif %}
    <span class="current">
        Strona {{ page.number }} z {{ page.paginator.num_pages }}.
    </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Następna</a>
        {% endif %}
    </span>
</div>

templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Opublikowany {{ post.title }} przez {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url "blog:post_share" post.id %}">Udostepnij post</a>
    </p>


    <h2>Podobne posty</h2>
    {% for post in similiar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        Nie ma podobnych postow.
    {% endfor %}


    {% with comments.count as total_comments %}
    <h2>{{ total_comments }} komentarz{{ total_comments|pluralize:"y" }}</h2>
    {% endwith %}
    {% for comment in comments %}
        <div class = "comment">
            <p class = "info">
                Komentarz {{ forloop.counter }} dodany przez  {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
        {% empty %}
        <p>Nie ma jeszcze żadnych komentarzy.</p>
    {% endfor %}
    {% if new_comment %}
        <h2> Twój komentarz został dodany. </h2>
    {% else %}
        <h2>Dodaj nowy komentarz.</h2>
        <form action="." method="post">
        {{ comment_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Dodaj komentarz"></p>
        </form>
    {% endif %}
{% endblock %}

templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href = "{{ post.get_absolute_url }}"> {{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}Super blog list {% endblock %}

    {% block content %}
    <h1>SuperBlog Demo</h1>
        {% if tag %}
        <h2>Posty oznaczone tagiem "{{ tag.name }}"</h2>
        {% endif %}
        {% for post in posts %}
            <h2>
                <a href ="{{ post.get_absolute_url }}"> {{ post.title }} </a>
                <p class ="tags">Tagi:
                {% for tag in post.tags.all %}
                    <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                    {{ tag.name }}
                    </a>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
                </p>
            </h2>
        <p class="date"> Opublikowany {{ post.publish }} przez {{ post.author }} </p>
        {{ post.body|markdown|truncatewords:30 }}
         {% endfor %}
{% include "blog/pagination.html" with page=posts %}
{% endblock %}

templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}A czego poszukujesz?{% endblock %}

{% block content %}
    {% if query %}
        <h1>Posty zawierające "{{ query }}"</h1>
        <h3>Znaleziono {{ total_results }} wynik {{ total_results|pluralize:"i" }}</h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            {{ post.body|markdown|truncatewords_html:5 }}
        {% empty %}
            <p> Brak wyników wyszukiwania</p>
        {% endfor %}
        <p><a href="{% url "blog:post_search" %}">Szukaj ponownie:</a></p>
    {% else %}
    <h1>Szukaj postów:</h1>
    <form method="get">
        {{ form.as_p }}
    <input type="submit" value="Szukaj">
    </form>
    {% endif %}
{% endblock %}

templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Udostepnij post {% endblock %}

{% block content %}
{% if sent %}
    <h1> Wiadomosc email zostala wyslana</h1>
    <p>
        Wyslanie posta " {{ post.title }} " przez e-mail.
    </p>
{% else %}
    <h1> Udostepnij " {{ post.title }} " przez e-mail.</h1>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Wyslij wiadmosc e-mail">
    </form>
{% endif %}
{% endblock %}